### ISSUE TITLE
Please add the animations

### ISSUE THREAD

**Issue by leon** [mhevery/ng-google-io#1]
i'm particulary interested in how you did the mobile slide in, slide out.

:+1:

**Comment by dpicky** [comment]
+1 on the animations

**Comment by kvnwolf** [comment]
Hello, @leon @dpicky, you can see the slide in-out animations on this file: https://github.com/mhevery/ng-google-io/blob/demo/app/scripts/main.js#L22 (it was on the `demo` branch).

**Comment by leon** [comment]
Haha... never thought about looking to see if there was another branch. Thanks @kevin-wolf!
